# Generated by Django 5.0 on 2025-01-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='is_active',
        ),
    ]
