# Generated by Django 5.0 on 2025-01-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_remove_branch_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='type_organization',
            field=models.CharField(blank=True, choices=[('school', 'school'), ('university', 'university'), ('kinder_garden', 'kinder_garden')], max_length=255, null=True),
        ),
    ]
