# Generated by Django 5.0 on 2025-01-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_branch_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='location',
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
