# Generated by Django 5.2.1 on 2025-07-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi [title]")),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]")),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]")),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]")),
                ('content', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('content_uz', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('image', models.ImageField(blank=True, null=True, upload_to='planners', verbose_name='Rasm [image]')),
            ],
            options={
                'verbose_name': 'Planner',
                'verbose_name_plural': 'Planners',
                'db_table': 'planners',
            },
        ),
    ]
