# Generated by Django 5.2.1 on 2025-05-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Tarkibi [image]'),
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
