# Generated by Django 5.2.1 on 2025-05-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image_delete_newsimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
