# Generated by Django 5.2.1 on 2025-05-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
    ]
