# Generated by Django 5.2.1 on 2025-05-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_content_en_news_content_ru_news_content_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi [title]")),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]")),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]")),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]")),
                ('content', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('content_uz', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati [is_active]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'db_table': 'faq',
            },
        ),
    ]
