# Generated by Django 5.0 on 2025-01-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_year', '0002_academicyear_is_active_classofbranch_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='classofbranch',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='documentsacademicyear',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_active',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classofbranch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classofbranch',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentsacademicyear',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsacademicyear',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
