# Generated by Django 5.2.1 on 2025-05-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi [title]")),
                ('content', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Rasm [image]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati [is_active]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Biz haqimizda',
                'verbose_name_plural': 'Biz haqimizda',
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi [title]")),
                ('content', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners', verbose_name='Rasm [logo]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati [is_active]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Partners',
                'verbose_name_plural': 'Partners',
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings', verbose_name='Rasm [logo]')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram [url]')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram [url]')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook [url]')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter [url]')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Youtube [url]')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp [text]')),
                ('phone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone 1 [text]')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone 2 [text]')),
                ('mail', models.CharField(blank=True, max_length=25, null=True, verbose_name='Mail [text]')),
                ('address1', models.CharField(blank=True, max_length=355, null=True, verbose_name='Address [text]')),
                ('address2', models.CharField(blank=True, max_length=355, null=True, verbose_name='Address [text]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Sozlamalar',
                'verbose_name_plural': 'Sozlamalar',
                'db_table': 'settings',
            },
        ),
    ]
