# Generated by Django 5.2.1 on 2025-05-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_solidfeature_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='DottedShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi [name]")),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [name]")),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [name]")),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [name]")),
                ('content', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('content_uz', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partners', verbose_name='Rasm [logo]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati [is_active]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Dotted Shape',
                'verbose_name_plural': 'Dotted Shape',
                'db_table': 'dotted_shape',
            },
        ),
    ]
