# Generated by Django 5.0 on 2025-01-16 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationOfEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('document_series', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('language_skill', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassportOfEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('document_number', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('work_position', models.CharField(blank=True, choices=[('teacher', 'teacher'), ('director', 'director'), ('hr', 'hr'), ('admission', 'admission'), ('cord_teacher', 'cord_teacher'), ('chief', 'chief'), ('doctor', 'doctor')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'new'), ('active', 'aactive'), ('inactive', 'inactive')], max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=400, null=True)),
                ('passport_file', models.FileField(blank=True, null=True, upload_to='employee/passport/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='employee/resume/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee/photo/')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('passport', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.passportofemployee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
