# Generated by Django 5.0 on 2025-01-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationofemployee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='passportofemployee',
            name='is_active',
        ),
    ]
