# Generated by Django 5.0 on 2025-01-17 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='education',
        ),
        migrations.AddField(
            model_name='educationofemployee',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'single'), ('married', 'married'), ('widowed', 'widowed'), ('divorced', 'divorced'), ('separated', 'separated')], max_length=255, null=True),
        ),
    ]
