# Generated by Django 5.0 on 2025-01-17 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employee_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='passport_file',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='resume',
        ),
        migrations.AddField(
            model_name='passportofemployee',
            name='is_id',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('file', models.FileField(blank=True, null=True, upload_to='employee/files/')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
