# Generated by Django 5.0 on 2025-01-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_employee_passport_file_remove_employee_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='educationofemployee',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='passportofemployee',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
