# Generated by Django 5.0 on 2025-01-23 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_remove_branch_location_branch_latitude_and_more'),
        ('employee', '0006_attachments_is_active_educationofemployee_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('active', 'active'), ('inactive', 'inactive')], max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('work_position', 'director')), fields=('branch', 'work_position'), name='unique_director_per_branch'),
        ),
    ]
