# Generated by Django 5.0 on 2025-01-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_director_per_branch',
        ),
    ]
