# Generated by Django 5.0 on 2025-01-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_remove_attachments_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationofemployee',
            name='employee',
        ),
    ]
