# Generated by Django 5.0 on 2025-02-03 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_employee_description_employee_hire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployementHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('beginning_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('still_working', models.BooleanField(blank=True, default=False, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.CharField(blank=True, max_length=500, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('employment', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('hybrid', 'Hybrid')], max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employement_history', to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
