# Generated by Django 5.0 on 2025-01-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_branch_student_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('active', 'aactive'), ('inactive', 'inactive')], max_length=255, null=True),
        ),
    ]
