# Generated by Django 5.0 on 2025-02-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_attachments_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='document',
            new_name='document_type',
        ),
    ]
