# Generated by Django 5.2.1 on 2025-05-21 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi [title]")),
                ('attr', models.CharField(max_length=255, verbose_name="To'liq nomi [attr]")),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_types', verbose_name='Rasm [image]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati [is_active]')),
            ],
            options={
                'verbose_name': 'Course type',
                'verbose_name_plural': 'Course type',
                'db_table': 'course_types',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name="To'liq ismi [name]")),
                ('position', models.CharField(max_length=255, verbose_name='lavozimi [position]')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='teachers', verbose_name='Rasm [avatar]')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('is_boss', models.BooleanField(default=False, verbose_name='Rahbar [is_boss]')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Xodim [is_staff]')),
                ('is_active', models.BooleanField(default=False, verbose_name='Holati [is_active]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Teachers',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi [title]")),
                ('content', models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses', verbose_name='Rasm [image]')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Video [url]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati [is_active]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('course_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.coursetype', verbose_name='Kurs turi [course_type]')),
                ('teacher', models.ManyToManyField(to='cours.teachers', verbose_name='Muallif [teacher]')),
            ],
            options={
                'verbose_name': 'Courses',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
            },
        ),
    ]
