# Generated by Django 5.2.1 on 2025-05-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='courses',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='courses',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='teachers',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='about_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='lavozimi [position]'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='lavozimi [position]'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='position_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='lavozimi [position]'),
        ),
    ]
