# Generated by Django 5.2.1 on 2025-07-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_courses_content_en_courses_content_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='Rang kodi'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=255, unique=True, verbose_name='URL slug'),
        ),
    ]
