districts = [
    {"region_id": 1,"name_uz":"Amudaryo tumani","name_cyr":"Амударё тумани","name_ru":"Амударьинский район"},
    {"region_id": 1,"name_uz":"Beruniy tumani","name_cyr":"Беруний тумани","name_ru":"Берунийский район"},
    {"region_id": 1,"name_uz":"Kegayli tumani","name_cyr":"Кегайли тумани","name_ru":"Кегейлийский район"},
    {"region_id": 1,"name_uz":"Qonliko‘l tumani","name_cyr":"Қонликўл тумани","name_ru":"Канлыкульский район"},
    {"region_id": 1,"name_uz":"Qorao‘zak tumani","name_cyr":"Қораўзак тумани","name_ru":"Караузякский район"},
    {"region_id": 1,"name_uz":"Qo‘ng‘irot tumani","name_cyr":"Қўнғирот тумани","name_ru":"Кунградский район"},
    {"region_id": 1,"name_uz":"Mo‘ynoq tumani","name_cyr":"Мўйноқ тумани","name_ru":"Муйнакский район"},
    {"region_id": 1,"name_uz":"Nukus tumani","name_cyr":"Нукус тумани","name_ru":"Нукусский район"},
    {"region_id": 1,"name_uz": "Nukus shahri","name_cyr": "Нукус шаҳри","name_ru": "город Нукус"},
    {"region_id": 1,"name_uz":"Taxtako‘pir tumani","name_cyr":"Тахтакўпир тумани","name_ru":"Тахтакупырский район"},
    {"region_id": 1,"name_uz":"To‘rtko‘l tumani","name_cyr":"Тўрткўл тумани","name_ru":"Турткульский район"},
    {"region_id": 1,"name_uz":"Xo‘jayli tumani","name_cyr":"Хўжайли тумани","name_ru":"Ходжейлийский район"},
    {"region_id": 1,"name_uz":"Chimboy tumani","name_cyr":"Чимбой тумани","name_ru":"Чимбайский район"},
    {"region_id": 1,"name_uz":"Shumanay tumani","name_cyr":"Шуманай тумани","name_ru":"Шуманайский район"},
    {"region_id": 1,"name_uz":"Ellikqal‘a tumani","name_cyr":"Элликқалъа тумани","name_ru":"Элликкалинский район"},
    {"region_id": 2,"name_uz": "Andijon shahri","name_cyr": "Андижон шаҳри","name_ru": "город Андижан"},
    {"region_id": 2,"name_uz":"Andijon tumani","name_cyr":"Андижон тумани","name_ru":"Андижанский район"},
    {"region_id": 2,"name_uz":"Asaka tumani","name_cyr":"Асака тумани","name_ru":"Асакинский район"},
    {"region_id": 2,"name_uz":"Baliqchi tumani","name_cyr":"Балиқчи тумани","name_ru":"Балыкчинский район"},
    {"region_id": 2,"name_uz":"Buloqboshi tumani","name_cyr":"Булоқбоши тумани","name_ru":"Булакбашинский район"},
    {"region_id": 2,"name_uz":"Bo‘z tumani","name_cyr":"Бўз тумани","name_ru":"Бозский район"},
    {"region_id": 2,"name_uz":"Jalaquduq tumani","name_cyr":"Жалақудуқ тумани","name_ru":"Джалакудукский район"},
    {"region_id": 2,"name_uz":"Izbosgan tumani","name_cyr":"Избосган тумани","name_ru":"Избасканский район"},
    {"region_id": 2,"name_uz": "Qorasuv shahri","name_cyr": "Қорасув шаҳри","name_ru": "город Карасув"},
    {"region_id": 2,"name_uz":"Qo‘rg‘ontepa tumani","name_cyr":"Қўрғонтепа тумани","name_ru":"Кургантепинский район"},
    {"region_id": 2,"name_uz":"Marhamat tumani","name_cyr":"Марҳамат тумани","name_ru":"Мархаматский район"},
    {"region_id": 2,"name_uz":"Oltinko‘l tumani","name_cyr":"Олтинкўл тумани","name_ru":"Алтынкульский район"},
    {"region_id": 2,"name_uz":"Paxtaobod tumani","name_cyr":"Пахтаобод тумани","name_ru":"Пахтаабадский район"},
    {"region_id": 2,"name_uz":"Ulug‘nor tumani","name_cyr":"Улуғнор тумани","name_ru":"Улугнорский район"},
    {"region_id": 2,"name_uz": "Xonabod tumani","name_cyr":"Хонабод тумани","name_ru": "город Ханабад"},
    {"region_id": 2,"name_uz":"Xo‘jaobod tumani","name_cyr":"Хўжаобод тумани","name_ru":"Ходжаабадский район"},
    {"region_id": 2,"name_uz":"Shahrixon tumani","name_cyr":"Шаҳрихон тумани","name_ru":"Шахриханский район"},
    {"region_id": 3,"name_uz": "Buxoro shahri","name_cyr":"Бухоро шаҳри","name_ru": "город Бухара"},
    {"region_id": 3,"name_uz":"Buxoro tumani","name_cyr":"Бухоро тумани","name_ru":"Бухарский район"},
    {"region_id": 3,"name_uz":"Vobkent tumani","name_cyr":"Вобкент тумани","name_ru":"Вабкентский район"},
    {"region_id": 3,"name_uz":"G‘ijduvon tumani","name_cyr":"Ғиждувон тумани","name_ru":"Гиждуванский район"},
    {"region_id": 3,"name_uz":"Jondor tumani","name_cyr":"Жондор тумани","name_ru":"Жондорский район"},
    {"region_id": 3,"name_uz":"Kogon tumani","name_cyr":"Когон тумани","name_ru":"Каганский район"},
    {"region_id": 3,"name_uz": "Kogon shahri","name_cyr":"Когон шаҳри","name_ru": "город Каган"},
    {"region_id": 3,"name_uz":"Qorako‘l tumani","name_cyr":"Қоракўл тумани","name_ru":"Каракульский район"},
    {"region_id": 3,"name_uz":"Qorovulbozor tumani","name_cyr":"Қоровулбозор тумани","name_ru":"Караулбазарский район"},
    {"region_id": 3,"name_uz":"Olot tumani","name_cyr":"Олот тумани","name_ru":"Алатский район"},
    {"region_id": 3,"name_uz":"Peshku tumani","name_cyr":"Пешку тумани","name_ru":"Пешкунский район"},
    {"region_id": 3,"name_uz":"Romitan tumani","name_cyr":"Ромитан тумани","name_ru":"Ромитанский район"},
    {"region_id": 3,"name_uz":"Shofirkon tumani","name_cyr":"Шофиркон тумани","name_ru":"Шафирканский район"},
    {"region_id": 4,"name_uz":"Arnasoy tumani","name_cyr":"Арнасой тумани","name_ru":"Арнасайский район"},
    {"region_id": 4,"name_uz":"Baxmal tumani","name_cyr":"Бахмал тумани","name_ru":"Бахмальский район"},
    {"region_id": 4,"name_uz":"G‘allaorol tumani","name_cyr":"Ғаллаорол тумани","name_ru":"Галляаральский район"},
    {"region_id": 4,"name_uz":"Do‘stlik tumani","name_cyr":"Дўстлик тумани","name_ru":"Дустликский район"},
    {"region_id": 4,"name_uz": "Sh.Rashidov tumani","name_cyr": "Ш.Рашидов тумани","name_ru": "Шараф-Рашидовский район"},
    {"region_id": 4,"name_uz": "Jizzax shahri","name_cyr":"Жиззах шаҳри","name_ru": "город Джизак"},
    {"region_id": 4,"name_uz":"Zarbdor tumani","name_cyr":"Зарбдор тумани","name_ru":"Зарбдарский район"},
    {"region_id": 4,"name_uz":"Zafarobod tumani","name_cyr":"Зафаробод тумани","name_ru":"Зафарабадский район"},
    {"region_id": 4,"name_uz":"Zomin tumani","name_cyr":"Зомин тумани","name_ru":"Зааминский район"},
    {"region_id": 4,"name_uz":"Mirzacho‘l tumani","name_cyr":"Мирзачўл тумани","name_ru":"Мирзачульский район"},
    {"region_id": 4,"name_uz":"Paxtakor tumani","name_cyr":"Пахтакор тумани","name_ru":"Пахтакорский район"},
    {"region_id": 4,"name_uz":"Forish tumani","name_cyr":"Фориш тумани","name_ru":"Фаришский район"},
    {"region_id": 4,"name_uz":"Yangiobod tumani","name_cyr":"Янгиобод тумани","name_ru":"Янгиабадский район"},
    {"region_id": 5,"name_uz":"G‘uzor tumani","name_cyr":"Ғузор тумани","name_ru":"Гузарский район"},
    {"region_id": 5,"name_uz":"Dehqonobod tumani","name_cyr":"Деҳқонобод тумани","name_ru":"Дехканабадский район"},
    {"region_id": 5,"name_uz":"Qamashi tumani","name_cyr":"Қамаши тумани","name_ru":"Камашинский район"},
    {"region_id": 5,"name_uz":"Qarshi tumani","name_cyr":"Қарши тумани","name_ru":"Каршинский район"},
    {"region_id": 5,"name_uz": "Qarshi shahri","name_cyr":"Қарши шаҳри","name_ru": "город Карши"},
    {"region_id": 5,"name_uz":"Kasbi tumani","name_cyr":"Касби тумани","name_ru":"Касбийский район"},
    {"region_id": 5,"name_uz":"Kitob tumani","name_cyr":"Китоб тумани","name_ru":"Китабский район"},
    {"region_id": 5,"name_uz":"Koson tumani","name_cyr":"Косон тумани","name_ru":"Касанский район"},
    {"region_id": 5,"name_uz":"Mirishkor tumani","name_cyr":"Миришкор тумани","name_ru":"Миришкорский район"},
    {"region_id": 5,"name_uz":"Muborak tumani","name_cyr":"Муборак тумани","name_ru":"Мубарекский район"},
    {"region_id": 5,"name_uz":"Nishon tumani","name_cyr":"Нишон тумани","name_ru":"Нишанский район"},
    {"region_id": 5,"name_uz":"Chiroqchi tumani","name_cyr":"Чироқчи тумани","name_ru":"Чиракчинский район"},
    {"region_id": 5,"name_uz":"Shahrisabz tumani","name_cyr":"Шаҳрисабз тумани","name_ru":"Шахрисабзский район"},
    {"region_id": 5,"name_uz":"Yakkabog‘ tumani","name_cyr":"Яккабоғ тумани","name_ru":"Яккабагский район"},
    {"region_id": 6,"name_uz": "Zarafshon shahri","name_cyr":"Зарафшон шаҳри","name_ru": "город Зарафшан"},
    {"region_id": 6,"name_uz":"Karman tumani","name_cyr":"Карман тумани","name_ru":"Карманинский район"},
    {"region_id": 6,"name_uz":"Qiziltepa tumani","name_cyr":"Қизилтепа тумани","name_ru":"Кызылтепинский район"},
    {"region_id": 6,"name_uz":"Konimex tumani","name_cyr":"Конимех тумани","name_ru":"Канимехский район"},
    {"region_id": 6,"name_uz":"Navbahor tumani","name_cyr":"Навбаҳор тумани","name_ru":"Навбахорский район"},
    {"region_id": 6,"name_uz": "Navoiy shahri","name_cyr":"Навоий шаҳри","name_ru": "город Навои"},
    {"region_id": 6,"name_uz":"Nurota tumani","name_cyr":"Нурота тумани","name_ru":"Нуратинский район"},
    {"region_id": 6,"name_uz":"Tomdi tumani","name_cyr":"Томди тумани","name_ru":"Тамдынский район"},
    {"region_id": 6,"name_uz":"Uchquduq tumani","name_cyr":"Учқудуқ тумани","name_ru":"Учкудукский район"},
    {"region_id": 6,"name_uz":"Xatirchi tumani","name_cyr":"Хатирчи тумани","name_ru":"Хатырчинский район"},
    {"region_id": 7,"name_uz":"Kosonsoy tumani","name_cyr":"Косонсой тумани","name_ru":"Касансайский район"},
    {"region_id": 7,"name_uz":"Mingbuloq tumani","name_cyr":"Мингбулоқ тумани","name_ru":"Мингбулакский район"},
    {"region_id": 7,"name_uz":"Namangan tumani","name_cyr":"Наманган тумани","name_ru":"Наманганский район"},
    {"region_id": 7,"name_uz": "Namangan shahri","name_cyr":"Наманган шаҳри","name_ru": "город Наманган"},
    {"region_id": 7,"name_uz":"Norin tumani","name_cyr":"Норин тумани","name_ru":"Нарынский район"},
    {"region_id": 7,"name_uz":"Pop tumani","name_cyr":"Поп тумани","name_ru":"Папский район"},
    {"region_id": 7,"name_uz":"To‘raqo‘rg‘on tumani","name_cyr":"Тўрақўрғон тумани","name_ru":"Туракурганский район"},
    {"region_id": 7,"name_uz":"Uychi tumani","name_cyr":"Уйчи тумани","name_ru":"Уйчинский район"},
    {"region_id": 7,"name_uz":"Uchqo‘rg‘on tumani","name_cyr":"Учқўрғон тумани","name_ru":"Учкурганский район"},
    {"region_id": 7,"name_uz":"Chortoq tumani","name_cyr":"Чортоқ тумани","name_ru":"Чартакский район"},
    {"region_id": 7,"name_uz":"Chust tumani","name_cyr":"Чуст тумани","name_ru":"Чустский район"},
    {"region_id": 7,"name_uz":"Yangiqo‘rg‘on tumani","name_cyr":"Янгиқўрғон тумани","name_ru":"Янгикурганский район"},
    {"region_id": 8,"name_uz":"Bulung‘ur tumani","name_cyr":"Булунғур тумани","name_ru":"Булунгурский район"},
    {"region_id": 8,"name_uz":"Jomboy tumani","name_cyr":"Жомбой тумани","name_ru":"Джамбайский район"},
    {"region_id": 8,"name_uz":"Ishtixon tumani","name_cyr":"Иштихон тумани","name_ru":"Иштыханский район"},
    {"region_id": 8,"name_uz":"Kattaqo‘rg‘on tumani","name_cyr":"Каттақўрғон тумани","name_ru":"Каттакурганский район"},
    {"region_id": 8,"name_uz": "Kattaqo‘rg‘on shahri","name_cyr":"Каттақўрғон шаҳри","name_ru": "город Каттакурган"},
    {"region_id": 8,"name_uz":"Qo‘shrabot tumani","name_cyr":"Қўшработ тумани","name_ru":"Кошрабадский район"},
    {"region_id": 8,"name_uz":"Narpay tumani","name_cyr":"Нарпай тумани","name_ru":"Нарпайский район"},
    {"region_id": 8,"name_uz":"Nurabod tumani","name_cyr":"Нурабод тумани","name_ru":"Нурабадский район"},
    {"region_id": 8,"name_uz":"Oqdaryo tumani","name_cyr":"Оқдарё тумани","name_ru":"Акдарьинский район"},
    {"region_id": 8,"name_uz":"Payariq tumani","name_cyr":"Паяриқ тумани","name_ru":"Пайарыкский район"},
    {"region_id": 8,"name_uz":"Pastarg‘om tumani","name_cyr":"Пастарғом тумани","name_ru":"Пастдаргомский район"},
    {"region_id": 8,"name_uz":"Paxtachi tumani","name_cyr":"Пахтачи тумани","name_ru":"Пахтачийский район"},
    {"region_id": 8,"name_uz":"Samarqand tumani","name_cyr":"Самарқанд тумани","name_ru":"Самаркандский район"},
    {"region_id": 8,"name_uz": "Samarqand shahri","name_cyr":"Самарқанд шаҳри","name_ru": "город Самарканд"},
    {"region_id": 8,"name_uz":"Toyloq tumani","name_cyr":"Тойлоқ тумани","name_ru":"Тайлакский район"},
    {"region_id": 8,"name_uz":"Urgut tumani","name_cyr":"Ургут тумани","name_ru":"Ургутский район"},
    {"region_id": 9,"name_uz":"Angor tumani","name_cyr":"Ангор тумани","name_ru":"Ангорский район"},
    {"region_id": 9,"name_uz":"Boysun tumani","name_cyr":"Бойсун тумани","name_ru":"Байсунский район"},
    {"region_id": 9,"name_uz":"Denov tumani","name_cyr":"Денов тумани","name_ru":"Денауский район"},
    {"region_id": 9,"name_uz":"Jarqo‘rg‘on tumani","name_cyr":"Жарқўрғон тумани","name_ru":"Джаркурганский район"},
    {"region_id": 9,"name_uz":"Qiziriq tumani","name_cyr":"Қизириқ тумани","name_ru":"Кизирикский район"},
    {"region_id": 9,"name_uz":"Qo‘mqo‘rg‘on tumani","name_cyr":"Қўмқўрғон тумани","name_ru":"Кумкурганский район"},
    {"region_id": 9,"name_uz":"Muzrabot tumani","name_cyr":"Музработ тумани","name_ru":"Музрабадский район"},
    {"region_id": 9,"name_uz":"Oltinsoy tumani","name_cyr":"Олтинсой тумани","name_ru":"Алтынсайский район"},
    {"region_id": 9,"name_uz":"Sariosiy tumani","name_cyr":"Сариосий тумани","name_ru":"Сариасийский район"},
    {"region_id": 9,"name_uz":"Termiz tumani","name_cyr":"Термиз тумани","name_ru":"Термезский район"},
    {"region_id": 9,"name_uz": "Termiz shahri","name_cyr":"Термиз шаҳри","name_ru": "город Термез"},
    {"region_id": 9,"name_uz":"Uzun tumani","name_cyr":"Узун тумани","name_ru":"Узунский район"},
    {"region_id": 9,"name_uz":"Sherobod tumani","name_cyr":"Шеробод тумани","name_ru":"Шерабадский район"},
    {"region_id": 9,"name_uz":"Sho‘rchi tumani","name_cyr":"Шўрчи тумани","name_ru":"Шурчинский район"},
    {"region_id": 10,"name_uz":"Boyovut tumani","name_cyr":"Боёвут тумани","name_ru":"Баяутский район"},
    {"region_id": 10,"name_uz":"Guliston tumani","name_cyr":"Гулистон тумани","name_ru":"Гулистанский район"},
    {"region_id": 10,"name_uz": "Guliston shahri","name_cyr":"Гулистон шаҳри","name_ru": "город Гулистан"},
    {"region_id": 10,"name_uz":"Mirzaobod tumani","name_cyr":"Мирзаобод тумани","name_ru":"Мирзаабадский район"},
    {"region_id": 10,"name_uz":"Oqoltin tumani","name_cyr":"Оқолтин тумани","name_ru":"Акалтынский район"},
    {"region_id": 10,"name_uz":"Sayxunobod tumani","name_cyr":"Сайхунобод тумани","name_ru":"Сайхунабадский район"},
    {"region_id": 10,"name_uz":"Sardoba tumani","name_cyr":"Сардоба тумани","name_ru":"Сардобский район"},
    {"region_id": 10,"name_uz":"Sirdaryo tumani","name_cyr":"Сирдарё тумани","name_ru":"Сырдарьинский район"},
    {"region_id": 10,"name_uz":"Xavos tumani","name_cyr":"Хавос тумани","name_ru":"Хавастский район"},
    {"region_id": 10,"name_uz": "Shirin shahri","name_cyr": "Ширин шаҳри","name_ru": "город Ширин"},
    {"region_id": 10,"name_uz": "Yangiyer shahri","name_cyr": "Янгиер шаҳри","name_ru": "город Янгиер"},
    {"region_id": 11,"name_uz": "Angiren shahri","name_cyr": "Ангирен шаҳри","name_ru": "город Ангрен"},
    {"region_id": 11,"name_uz":"Bekabod tumani","name_cyr":"Бекабод тумани","name_ru":"Бекабадский район"},
    {"region_id": 11,"name_uz": "Bekabod shahri","name_cyr": "Бекабод шаҳри","name_ru": "город Бекабад"},
    {"region_id": 11,"name_uz":"Bo‘ka tumani","name_cyr":"Бўка тумани","name_ru":"Букинский район"},
    {"region_id": 11,"name_uz":"Bo‘stonliq tumani","name_cyr":"Бўстонлиқ тумани","name_ru":"Бостанлыкский район"},
    {"region_id": 11,"name_uz":"Zangiota tumani","name_cyr":"Зангиота тумани","name_ru":"Зангиатинский район"},
    {"region_id": 11,"name_uz":"Qibray tumani","name_cyr":"Қибрай тумани","name_ru":"Кибрайский район"},
    {"region_id": 11,"name_uz":"Quyichirchiq tumani","name_cyr":"Қуйичирчиқ тумани","name_ru":"Куйичирчикский район"},
    {"region_id": 11,"name_uz":"Oqqo‘rg‘on tumani","name_cyr":"Оққўрғон тумани","name_ru":"Аккурганский район"},
    {"region_id": 11,"name_uz": "Olmaliq shahri","name_cyr": "Олмалиқ шаҳри","name_ru": "город Алмалык"},
    {"region_id": 11,"name_uz":"Ohangaron tumani","name_cyr":"Оҳангарон тумани","name_ru":"Ахангаранский район"},
    {"region_id": 11,"name_uz":"Parkent tumani","name_cyr":"Паркент тумани","name_ru":"Паркентский район"},
    {"region_id": 11,"name_uz":"Piskent tumani","name_cyr":"Пискент тумани","name_ru":"Пскентский район"},
    {"region_id": 11,"name_uz":"O‘rtachirchiq tumani","name_cyr":"Ўртачирчиқ тумани","name_ru":"Уртачирчикский район"},
    {"region_id": 11,"name_uz":"Chinoz tumani","name_cyr":"Чиноз тумани","name_ru":"Чиназский район"},
    {"region_id": 11,"name_uz": "Chirchiq shahri","name_cyr": "Чирчиқ шаҳри","name_ru": "город Чирчик"},
    {"region_id": 11,"name_uz":"Yuqorichirchiq tumani","name_cyr":"Юқоричирчиқ тумани","name_ru":"Юкоричирчикский район"},
    {"region_id": 11,"name_uz":"Yangiyo‘l tumani","name_cyr":"Янгийўл тумани","name_ru":"Янгиюльский район"},
    {"region_id": 12,"name_uz":"Beshariq tumani","name_cyr":"Бешариқ тумани","name_ru":"Бешарыкский район"},
    {"region_id": 12,"name_uz":"Bog‘dod tumani","name_cyr":"Боғдод тумани","name_ru":"Багдадский район"},
    {"region_id": 12,"name_uz":"Buvayda tumani","name_cyr":"Бувайда тумани","name_ru":"Бувайдинский район"},
    {"region_id": 12,"name_uz":"Dang‘ara tumani","name_cyr":"Данғара тумани","name_ru":"Дангаринский район"},
    {"region_id": 12,"name_uz":"Yozyovon tumani","name_cyr":"Ёзёвон тумани","name_ru":"Язъяванский район"},
    {"region_id": 12,"name_uz":"Quva tumani","name_cyr":"Қува тумани","name_ru":"Кувинский район"},
    {"region_id": 12,"name_uz": "Quvasoy shahri","name_cyr": "Қувасой шаҳри","name_ru": "город Кувасай"},
    {"region_id": 12,"name_uz": "Qo‘qon shahri","name_cyr": "Қўқон шаҳри","name_ru": "город Коканд"},
    {"region_id": 12,"name_uz":"Qo‘shtepa tumani","name_cyr":"Қўштепа тумани","name_ru":"Куштепинский район"},
    {"region_id": 12,"name_uz": "Marg‘ilon shahri","name_cyr": "Марғилон шаҳри","name_ru": "город Маргилан"},
    {"region_id": 12,"name_uz":"Oltiariq tumani","name_cyr":"Олтиариқ тумани","name_ru":"Алтыарыкский район"},
    {"region_id": 12,"name_uz":"Rishton tumani","name_cyr":"Риштон тумани","name_ru":"Риштанский район"},
    {"region_id": 12,"name_uz":"So‘x tumani","name_cyr":"Сўх тумани","name_ru":"Сохский район"},
    {"region_id": 12,"name_uz":"Toshloq tumani","name_cyr":"Тошлоқ тумани","name_ru":"Ташлакский район"},
    {"region_id": 12,"name_uz":"Uchko‘prik tumani","name_cyr":"Учкўприк тумани","name_ru":"Учкуприкский район"},
    {"region_id": 12,"name_uz":"O‘zbekiston tumani","name_cyr":"Ўзбекистон тумани","name_ru":"Узбекистанский район"},
    {"region_id": 12,"name_uz":"Farg‘ona tumani","name_cyr":"Фарғона тумани","name_ru":"Ферганский район"},
    {"region_id": 12,"name_uz": "Farg‘ona shahri","name_cyr": "Фарғона шаҳри","name_ru": "город Фергана"},
    {"region_id": 12,"name_uz":"Furqat tumani","name_cyr":"Фурқат тумани","name_ru":"Фуркатский район"},
    {"region_id": 13,"name_uz":"Bog‘ot tumani","name_cyr":"Боғот тумани","name_ru":"Багатский район"},
    {"region_id": 13,"name_uz":"Gurlan tumani","name_cyr":"Гурлан тумани","name_ru":"Гурленский район"},
    {"region_id": 13,"name_uz":"Qo‘shko‘pir tumani","name_cyr":"Қўшкўпир тумани","name_ru":"Кошкупырский район"},
    {"region_id": 13,"name_uz":"Urganch tumani","name_cyr":"Урганч тумани","name_ru":"Ургенчский район"},
    {"region_id": 13,"name_uz": "Urganch shahri","name_cyr": "Урганч шаҳри","name_ru": "город Ургенч"},
    {"region_id": 13,"name_uz":"Xiva tumani","name_cyr":"Хива тумани","name_ru":"Хивинский район"},
    {"region_id": 13,"name_uz":"Xazarasp tumani","name_cyr":"Хазарасп тумани","name_ru":"Хазараспский район"},
    {"region_id": 13,"name_uz":"Xonqa tumani","name_cyr":"Хонқа тумани","name_ru":"Ханкинский район"},
    {"region_id": 13,"name_uz":"Shavot tumani","name_cyr":"Шавот тумани","name_ru":"Шаватский район"},
    {"region_id": 13,"name_uz":"Yangiariq tumani","name_cyr":"Янгиариқ тумани","name_ru":"Янгиарыкский район"},
    {"region_id": 13,"name_uz":"Yangibozor tumani","name_cyr":"Янгибозор тумани","name_ru":"Янгибазарский район"},
    {"region_id": 14,"name_uz":"Bektimer tumani","name_cyr":"Бектимер тумани","name_ru":"Бектемирский район"},
    {"region_id": 14,"name_uz":"Mirzo Ulug'bek tumani","name_cyr": "Мuрзо-Улугбекский район", "name_ru": "Мирзо-Улугбекский район"},
    {"region_id": 14,"name_uz":"Mirobod tumani","name_cyr":"Миробод тумани","name_ru":"Мирабадский район"},
    {"region_id": 14,"name_uz":"Olmazor tumani","name_cyr":"Олмазор тумани","name_ru":"Алмазарский район"},
    {"region_id": 14,"name_uz":"Sirg'ali tuman","name_cyr":"Сиргали тумани","name_ru":"Сергелийский район"},
    {"region_id": 14,"name_uz":"Uchtepa tumani","name_cyr":"Учтепа тумани","name_ru":"Учтепинский район"},
    {"region_id": 14,"name_uz":"Yashnobod tumani","name_cyr":"Яшнобод тумани","name_ru":"Яшнободский район"},
    {"region_id": 14,"name_uz":"Chilonzor tumani","name_cyr":"Чилонзор тумани","name_ru":"Чиланзарский район"},
    {"region_id": 14,"name_uz":"Shayxontohur tumani","name_cyr":"Шайхонтоҳур тумани","name_ru":"Шайхантахурский район"},
    {"region_id": 14,"name_uz":"Yunusobod tumani","name_cyr":"Юнусобод тумани","name_ru":"Юнусабадский район"},
    {"region_id": 14,"name_uz":"Yakkasaroy tumani","name_cyr":"Яккасарой тумани","name_ru":"Яккасарайский район"},
    {"region_id": 1,"name_uz":"Taxiatosh shahri","name_cyr":"Тахиатош шаҳри","name_ru":"Тахиаташский район"},
    {"region_id": 2,"name_uz":"Asaka shahri","name_cyr":"Асака шаҳри","name_ru":"Асакинский район"},
    {"region_id": 9,"name_uz":"Bandixon tumani","name_cyr":"Бандихон тумани","name_ru":"Бандиханский район"},
    {"region_id": 11,"name_uz": "Ohangaron shahri","name_cyr": "Оҳангарон шаҳри","name_ru": "город Ахангаранский"},
    {"region_id": 11,"name_uz": "Yangiyo‘l shahri","name_cyr": "Янгийўл шаҳри","name_ru": "город Янгиюль"},
    {"region_id": 1,"name_uz":"Toshkent tumani","name_cyr":"Тошкент тумани","name_ru":"Ташкентский район"},
    {"region_id": 13,"name_uz": "Xiva shahri","name_cyr": "Хива шаҳри","name_ru": "город Хива"},
    {"region_id": 13,"name_uz": "Do'stlik shahri","name_cyr": "Дўстлик шаҳри Дўстлик шаҳри","name_ru": "город Дўстлик Дўстлик"},
    {"region_id": 4,"name_uz":"Yangihayot tumani","name_cyr":"Янгиҳаёт тумани","name_ru":"Янгихаётский район"},
    {"region_id": 3,"name_uz":"Tuproqqala tumani","name_cyr":"Тупроққалъа тумани","name_ru":"Тироккальский район"},
    {"region_id": 7,"name_uz": "Davlatobod tumani","name_cyr":"Давлатобод тумани","name_ru": "Давлатабадский район"},
    {"region_id": 6,"name_uz": "G‘ozg‘on shahri","name_cyr":"Ғозғон шаҳри","name_ru": "Город Гозган"},
    {"region_id": 1,"name_uz":"Bo‘zatov tumani","name_cyr":"Бўзатов тумани","name_ru":"Бозатовский район"},
    {"region_id": 9,"name_uz":"Bandixon tumani","name_cyr":"Бандихон тумани","name_ru":"Бандиксонский район"},
    {"region_id": 5,"name_uz": "Shahrisabz shahri","name_cyr": "Шаҳрисабз шаҳри","name_ru": "Город Шахрисабз"},
]