# Generated by Django 5.2.1 on 2025-05-17 15:17

import ckeditor_uploader.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi [title]")),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Rasm [image]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati [is_active]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Biz haqimizda',
                'verbose_name_plural': 'Biz haqimizda',
                'db_table': 'tesol_about',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi [title]")),
                ('attr', models.CharField(max_length=255, verbose_name="To'liq nomi [attr]")),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati [is_active]')),
            ],
            options={
                'verbose_name': 'Course type',
                'verbose_name_plural': 'Course type',
                'db_table': 'tesol_course_types',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID [uuid]')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi [title]")),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Rasm [image]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati [is_active]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('published_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'tesol_news',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi [title]")),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners', verbose_name='Rasm [logo]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati [is_active]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Partners',
                'verbose_name_plural': 'Partners',
                'db_table': 'tesol_partners',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings', verbose_name='Rasm [logo]')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram [url]')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram [url]')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook [url]')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter [url]')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Youtube [url]')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp [text]')),
                ('phone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone 1 [text]')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone 2 [text]')),
                ('mail', models.CharField(blank=True, max_length=25, null=True, verbose_name='Mail [text]')),
                ('address1', models.CharField(blank=True, max_length=355, null=True, verbose_name='Address [text]')),
                ('address2', models.CharField(blank=True, max_length=355, null=True, verbose_name='Address [text]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Sozlamalar',
                'verbose_name_plural': 'Sozlamalar',
                'db_table': 'tesol_settings',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name="To'liq ismi [name]")),
                ('position', models.CharField(max_length=255, verbose_name='lavozimi [position]')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='teachers', verbose_name='Rasm [avatar]')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('is_boss', models.BooleanField(default=False, verbose_name='Rahbar [is_boss]')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Xodim [is_staff]')),
                ('is_active', models.BooleanField(default=False, verbose_name='Holati [is_active]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Teachers',
                'verbose_name_plural': 'Teachers',
                'db_table': 'tesol_teachers',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Rasm [image]')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tesol.news', verbose_name='Yangilik [news]')),
            ],
            options={
                'verbose_name': 'Yangilik rasmi',
                'verbose_name_plural': 'Yangiliklar rasmlari',
                'db_table': 'tesol_news_images',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi [title]")),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Tarkibi [content]')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses', verbose_name='Rasm [image]')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Video [url]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati [is_active]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('course_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesol.coursetype', verbose_name='Kurs turi [course_type]')),
                ('teacher', models.ManyToManyField(to='tesol.teachers', verbose_name='Muallif [teacher]')),
            ],
            options={
                'verbose_name': 'Courses',
                'verbose_name_plural': 'Courses',
                'db_table': 'tesol_courses',
            },
        ),
    ]
