# Generated by Django 5.2.1 on 2025-05-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesol', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
