# Generated by Django 5.2.1 on 2025-05-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesol', '0003_alter_about_content_alter_courses_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='about',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='about',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='about',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='about',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='courses',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='courses',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='courses',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='partners',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='partners',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='partners',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='partners',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='partners',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='partners',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='teachers',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='about_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='lavozimi [position]'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='lavozimi [position]'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='position_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='lavozimi [position]'),
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Tarkibi [content]'),
        ),
    ]
