# Generated by Django 5.2.1 on 2025-05-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesol', '0004_remove_news_image_about_content_en_about_content_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
