# Generated by Django 5.2.1 on 2025-05-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesol', '0005_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_types', verbose_name='Rasm [image]'),
        ),
    ]
