# Generated by Django 5.2.1 on 2025-07-01 12:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesol', '0008_services_courses_order_teachers_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kategoriya nomi [title]')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsifi [description]')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL slug [slug]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati [is_active]')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami [order]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Gallery kategoriyasi',
                'verbose_name_plural': 'Gallery kategoriyalari',
                'db_table': 'tesol_gallery_categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID [uuid]')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha [title]')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsifi [description]')),
                ('media_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video'), ('file', 'Fayl')], default='image', max_length=10, verbose_name='Media turi [media_type]')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Rasm [image]')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='gallery/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm'])], verbose_name='Video fayl [video_file]')),
                ('video_url', models.URLField(blank=True, help_text='YouTube yoki Vimeo video havolasi', null=True, verbose_name='Video URL (YouTube, Vimeo) [video_url]')),
                ('file_url', models.FileField(blank=True, null=True, upload_to='gallery/files/', verbose_name='Fayl [file_url]')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Tashqi havola [external_url]')),
                ('alt_text', models.CharField(blank=True, help_text='Rasm uchun alternativ matn (SEO va accessibility)', max_length=255, null=True, verbose_name='Alt matn [alt_text]')),
                ('tags', models.CharField(blank=True, help_text='Vergul bilan ajratilgan teglar', max_length=500, null=True, verbose_name='Teglar [tags]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati [is_active]')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan [is_featured]')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami [order]')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rilgan soni [view_count]")),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr sanasi [published_at]')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesol.gallerycategory', verbose_name='Kategoriya [category]')),
            ],
            options={
                'verbose_name': 'Gallery elementi',
                'verbose_name_plural': 'Gallery',
                'db_table': 'tesol_gallery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='tesol.gallery')),
            ],
            options={
                'verbose_name': "Gallery ko'rish",
                'verbose_name_plural': "Gallery ko'rishlar",
                'db_table': 'tesol_gallery_views',
                'unique_together': {('gallery', 'ip_address')},
            },
        ),
    ]
