# Generated by Django 5.2.1 on 2025-07-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesol', '0009_gallerycategory_gallery_galleryview'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi [description]'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi [description]'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi [description]'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha [title]'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha [title]'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha [title]'),
        ),
    ]
